Eodhp 231 test kube system environment test suites
UKEODHP/eodhp-system-tests pull request #1
Opened 2024-03-25 16:17 UTC by SerkanDural

This PR includes all changes done with in the scope of JIRA Story (https://telespazio-uk.atlassian.net/browse/EODHP-231) includes commits related to sample test suite, which includes some sample test executions and delay between test executions.

Updates in the Readme file:
- how to create, execute, update and delete the test suites
- testsuite shell script which creates the test suite,
- modifications in tests related to the updates in the url of the components

Various sample tests are created and executed with in the scope of EODHP-231, but their results are not saved, only done for testsuite testing purposes.

2024-03-26 15:47 UTC, sgillies-tpzuk requested changes
I still have concerns about how easy this is going to be to quickly load in all tests and run test suites. I have suggested some changes that will mitigate this to some extend.

We should have one set of parameterised tests for all environments. We can then create one test suite per environment that defines the variables.

The main concern for me is I see no easy way to add or update all tests from the CLI. If they are added as part of a test suite then that's great, but from the documentation it does not seem like this is the case. I'm not particularly keen on a shell script to do it because then we have to remember to add new tests to the script. And if we need another script to update them all then that's even messier.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on envs/testsuite/eodhp-testsuite.sh
It should be possible to define the test suites as a file, e.g. test-suites/dev.json. You can then use a command like `cat test-suites/dev.json | kubectl testkube create testsuite` to load it into test suite. We want to keep the environment test suites tracked in git, we don't want the user to have to manually create and update them.

This way the json file will be nicely formatted and syntax highlighted. It can also be parsed and autoformatted.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on README.md
Markdown formatting on this page is inconsistent. Please use a formatter such as `prettier` and use it to autoformat code.

There are hanging list items, e.g.
```
- item 1
- item 2
-
```

I do not think `> - ` is valid markdown, please just use `-` for all unordered lists.

The number of `#` before a heading indicates whether it is h1, h2, h3... You have used h1 everywhere. h1 should only be used for title at the top. Everywhere else it should be maximum h2, but also use h3, h4, h5 and h6 to indicate subheadings where appropriate.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on README.md
> +``` testkube update test --name <testname> ```
Triple backtick is for code blocks (multiline). Please use single backticks for single line code. If you wish to use a code block even for a single line (which is fine) then please put triple backticks on line above and below.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on README.md
> +optionally add ``` -f ``` option to wait until the execution complete
use single backticks here for inline code block.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on envs/test/apphub/curl/testexecute.sh
this file serves no practical purpose other than documentation. Better to just document these commands in readme.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on README.md
README would be better cut down to focus more on how to run the tests in this repo. User can check testkube docs for more general documentation. You can add a link to the homepage of testkube docs, but I don't think you need to post so many links.

What I would want to see is a developer is:
```
# EODHP System Tests

## Test Suites
### Create Test Suite
#### From File
...

#### From Repo
...

### Run Test Suite
...

### Update Test Suite
...

## Tests
### Create Tests
#### From File
...

#### From Repo
...

### Run Tests
...

### Update Tests
...
```

Do all tests need to be added before you can run a test suite? Or does adding the test suite add all of the tests? Adding all of the tests individually isn't going to be feasible, so we need to automate that somehow if they cant be added by a test suite.

2024-03-26 15:47 UTC, sgillies-tpzuk commented on envs/dev/apphub/apphub-test1.json
all of these tests have common parameters like the base URL hard coded. This means we need different tests for different environments. You can redefine the tests to look like 

```
{
  "command": [
    "curl",
    "${BASE_URL}/vs"
  ],
  "expected_status": "200"
}
```

and pass variables with `testkube run test eoxvs-curl-base --variable BASE_URL=https://test.eodatahub.org.uk`. That way we can only have one set of tests and test suites for each different environment. I think variables can be set in test suites, although the documentation does not give any examples.

I suggest you refactor all existing tests to be in `tests/<app>` and parameterise them so they take inputs.

2024-03-27 08:42 UTC, SerkanDural commented on README.md
> +optionally add ``` -f ``` option to wait until the execution complete
Agreed

2024-03-27 08:49 UTC, SerkanDural commented on README.md
> +``` testkube update test --name <testname> ```
Ok, fixed

2024-03-27 08:52 UTC, SerkanDural commented on README.md
Fixed as suggested

2024-03-27 08:52 UTC, SerkanDural commented on README.md
updated as suggested

2024-03-27 08:54 UTC, SerkanDural commented on envs/test/apphub/curl/testexecute.sh
These commands are already in Readme in relevant sections

2024-03-27 08:55 UTC, SerkanDural commented on envs/testsuite/eodhp-testsuite.sh
Thanks for the suggestion. If it is clearer that way, I will update the testsuite folder content

2024-03-27 10:29 UTC, SerkanDural commented on README.md
updated as suggested

2024-03-27 10:30 UTC, SerkanDural commented on README.md
> +``` testkube update test --name <testname> ```
updated as suggested

2024-03-27 10:30 UTC, SerkanDural commented on README.md
> +optionally add ``` -f ``` option to wait until the execution complete
updated as suggested

2024-03-27 15:54 UTC, SerkanDural commented on envs/testsuite/eodhp-testsuite.sh
We can keep the test names and test json file names fixed. So, we can only update the tests using testkube test update command. 

`testkube update test --file <testjsonfilepath> --name <testname>`

So the update command will not change in every test update. It will be same and we will not be updating the test suite just because the test content is updated.

2024-03-27 16:46 UTC, ahaywardtvuk reviewed
Are we able to use the Testkube ArgoCD integration described at https://docs.testkube.io/articles/argocd-integration ? This generates Testkube CRDs by scanning a git repo containing the test definitions. The tests are then also visible in the ArgoCD UI. I'm not sure what we can _do_ with them in ArgoCD, but if we can trigger them and see their pass/fail status then that would be very helpful.

If we can get the tests into the cluster this way, and especially if we can add labels to them, then we have a chance of being able to run them in an automated way by getting a list of them with a `kubectl` command and piping this into `testkube run`.

BTW, it looks like the dashboard is a 'pro' feature and they've recently changed the licensing in the repo so that the pro parts aren't under an MIT licence any more. I don't think we're allowed to run the dashboard without paying unless we stay with only 3 users and 1 environment.

I've created EODHP-245 (to investigate alternatives) with a list of the things I think we want from such a tool which may be worth a look. If we can do all those things then Testkube may still be a contender.

2024-03-28 12:17 UTC, sgillies-tpzuk reviewed
Is this really ready for review again? None of the tests have been parameterised and some of them still have the old URLs in them?

Please request a re-review from me using refresh icon beside my name when this is ready to review.

2024-03-28 12:23 UTC, SerkanDural commented
> Is this really ready for review again? None of the tests have been parameterised and some of them still have the old URLs in them?
> 
> Please request a re-review from me using refresh icon beside my name when this is ready to review.

No, not ready for review yet. I will make it ready by end of today.

2024-04-02 08:29 UTC, sgillies-tpzuk approved these changes

2024-04-02 09:27 UTC, merged